# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20160520_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
