# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20160520_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 22, 10, 27, 42, 244644), null=True),
        ),
    ]
