# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20160522_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 22, 12, 20, 53, 645082), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 22, 12, 20, 53, 643323), null=True),
        ),
    ]
