# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_auto_20160522_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 22, 13, 20, 55, 829240, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 22, 13, 21, 34, 685251, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
